"""notifications/push/follows/social_oauth + reminders offset+delivered

Revision ID: 7a9fffab70f6
Revises: 
Create Date: 2025-09-13 03:35:05.079246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9fffab70f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('push_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('social_identities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=191), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('raw_profile_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_uid')
    )
    with op.batch_alter_table('social_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_identities_user_id'), ['user_id'], unique=False)

    op.create_table('user_follows',
    sa.Column('follower_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('following_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('host_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('tournament_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offset_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)

    with op.batch_alter_table('team_followers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('team_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
        batch_op.alter_column('owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('team_followers', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('offset_minutes')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.alter_column('tournament_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('host_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('user_follows')
    with op.batch_alter_table('social_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_identities_user_id'))

    op.drop_table('social_identities')
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_tokens_user_id'))

    op.drop_table('push_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
